apiVersion: v2
appVersion: 1.18.0
dependencies:
- condition: tags.minio
  name: minio
  repository: https://charts.min.io/
  version: 4.0.15
- name: dex
  repository: https://charts.dexidp.io
  version: 0.6.3
- name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.9.1
description: A Helm chart for Zadig
name: zadig
type: application
version: 1.18.0
