apiVersion: v1
kind: Service
metadata:
  name: aslan
  labels:
    {{- include "zadig.microservice.aslan.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ template "zadig.microservice.aslan.port" . }}
      targetPort: {{ template "zadig.microservice.aslan.port" . }}
      name: svc
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: pprof
  selector:
    {{- include "zadig.microservice.aslan.selectorLabels" . | nindent 4 }}
