---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-argocd-server
  namespace: argocd
spec:
  volumeMode: Filesystem
  storageClassName: juice-fs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: argocd
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: argocd.devops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cluster-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cluster-cm
    app.kubernetes.io/part-of: argocd
